name: Deploy Website

on:
  workflow_dispatch:
  push:
    paths:
      - 'website/**'
      - '.github/workflows/deploy-website.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup rsync and SSH
        run: sudo apt-get update && sudo apt-get install -y rsync openssh-client

      - name: Add SSH key
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          printf "Host target\n  HostName %s\n  User %s\n  Port %s\n  IdentityFile ~/.ssh/id_ed25519\n  StrictHostKeyChecking no\n" "$SSH_HOST" "$SSH_USER" "$SSH_PORT" > ~/.ssh/config
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PORT: ${{ secrets.SSH_PORT }}

      - name: Rsync website
        run: |
          rsync -avz --delete --chmod=Du=rwx,Dg=rx,Do=rx,Fu=rw,Fg=r,Fo=r website/ target:${{ secrets.WEB_ROOT }}/

      - name: Touch index to bust caches
        run: ssh target "sudo find ${{ secrets.WEB_ROOT }} -type f -name 'index.html' -exec touch {} + || true"
